application: pypest
version: master
runtime: python27
api_version: 1
threadsafe: true


libraries:
- name: numpy
  version: latest
- name: django
  version: "1.5"
- name: PIL
  version: latest
- name: matplotlib
  version: latest
- name: ssl
  version: latest

builtins:
- django_wsgi: on

env_variables:
  UBERTOOL_BATCH_SERVER: 'http://uberrest-topknotmeadows.rhcloud.com/'
  UBERTOOL_MONGO_SERVER: 'http://uberrest-topknotmeadows.rhcloud.com'
  UBERTOOL_SECURE_SERVER: 'http://uberrest-topknotmeadows.rhcloud.com'
  #UBERTOOL_REST_SERVER: 'http://localhost:80'
  UBERTOOL_REST_SERVER: 'http://54.83.18.251:80'
  PROJECT_PATH: ''
  SITE_SKIN: ''

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.gz
- ^(.*/)?.*\.aux
- ^(.*/)?.*\.xcf
- ^(.*/)?.*\.log
- ^(.*/)?.*\.rst
- ^(.*/)?.*\.doctree
- ^(.*/)?.*\.php
- ^(.*/)?.*\.bak
- ^(.*/)?.*\.inc
- ^(.*/)?.*\.dark
- ^(.*/)?.*\.nofill
- ^(.*/)?.*\.SDR
- ^(.*/)?.*\MIT-LICENSE
- ^(.*/)?.*\LGPL-LICENSE


handlers:
- url: /static
  static_dir: static
- url: /.*
  script: wsgi.application
